version: 2
jobs:
  build:
    working_directory: ~/ember-rails-example
    docker:
      - image: circleci/ruby:2.4
      # Circle's ruby+node+browsers image almost works for us,
      # but it has node 8, which ember doesn't support yet.
      # - image: circleci/ruby:2.4-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "frontend/yarn.lock" }}
      - restore_cache:
          keys:
            - v1-bundle-deps-{{ checksum "Gemfile.lock" }}
      - run:
          name: chrome-add-apt
          command: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run:
          name: chrome-apt-update
          command: sudo apt-get update
      - run:
          name: chrome-install
          command: sudo apt-get install google-chrome-stable
      - run:
          name: get-node
          command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - run:
          name: install-node
          command: sudo apt-get install -y nodejs
      - run:
          name: bundle
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-yarn-deps-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - save_cache:
          key: v1-bundle-deps-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: node-version
          command: node --version
      - run:
          name: ember-deps
          command: bundle exec rake ember:install
      - run:
          name: test
          command: bundle exec rspec
      - run:
          name: test-ember
          command: bundle exec rake ember:test